### ISSUE TITLE
Ntop

### ISSUE THREAD

**Issue by billy-boatright** [custodietmssp/Custodiet#1]
I emailed you guys about this last night, but then I thought we should use this from now on.  I got Ntop running natively on SO.  I can see all the traffic.  But I'm having trouble logging in to the admin portion of the web interface.  Without logging into that part, I can't tell if it can do the alerting we need.  Here is the link, so you guys don't have to search to help me: https://help.ubuntu.com/community/Ntop

Thanks,
Billy

**Comment by jmarpet** [comment]
I was able to install NTOP from the ubuntu software center inside SO.  It seems to work just fine.  I did have a problem, when I realized that the password for administrator on NTOP, and the SO password, and the Ubuntu (host OS) password are all different.  Argh.  Had to write them all down.  Well, actually, I made the NTOP and SO password the same.  Wonder if that's why mine worked?  

NTOP is pretty nice, BTW.

**Comment by billy-boatright** [comment]
I thought so too. Having never worked with these types of programs, I thought it would fit the bill. Problem is I can't seem to get into the admin section of the web interface. That is where I got stuck. 

Billy

**Comment by jmarpet** [comment]
I'll try it again tonight when I get home.  by the way I've got to do a
proposal for a first real paying client

**Comment by billy-boatright** [comment]
Score.  I'll play with it some more, now that I know it can work.

**Comment by billy-boatright** [comment]
I got into the admin console, but couldn't find anything for email alerting, yet.......

**Comment by billy-boatright** [comment]
After 5 hours, I can't seem to find anywhere to put an email address for alerts in NTOP.
